Repository natrontech/360-noscope, pull requests merged in 2023-08, with the labels that each got.

#5 feat: add survey pocketbase structure
  ui/pocketbase/pb_migrations/1692998131_created_dimensions.js
  ui/pocketbase/pb_migrations/1692998194_created_themes.js
  ui/pocketbase/pb_migrations/1692998216_updated_dimensions.js
  ui/pocketbase/pb_migrations/1692998232_updated_themes.js
  ui/pocketbase/pb_migrations/1692998316_created_survey_indicators.js
  ui/pocketbase/pb_migrations/1692998625_created_survey_question_types.js
  ui/pocketbase/pb_migrations/1692998665_created_survey_questions.js
  ui/pocketbase/pb_migrations/1692998765_updated_survey_questions.js
  ui/pocketbase/pb_migrations/1692998874_created_survey_answers.js
  ui/pocketbase/pb_migrations/1692998941_created_surveys.js
  ui/pocketbase/pb_migrations/1692999059_created_survey_fills.js
  ui/pocketbase/pb_migrations/1692999157_updated_survey_fills.js
Labels: ui, size/XL

#10 feat: enhance pocketbase collections
  ui/.DS_Store
  ui/frontend/src/lib/pocketbase/generated-types.ts
  ui/pocketbase/.DS_Store
  ui/pocketbase/pb_migrations/1693005297_updated_survey_fills.js
  ui/pocketbase/pb_migrations/1693005341_created_municipalities.js
  ui/pocketbase/pb_migrations/1693005390_updated_survey_fills.js
  ui/pocketbase/pb_migrations/1693005577_updated_municipalities.js
  ui/pocketbase/pb_migrations/1693005698_updated_survey_fills.js
  ui/pocketbase/pb_migrations/1693005724_deleted_survey_fills.js
  ui/pocketbase/pb_migrations/1693005729_deleted_survey_answers.js
  ui/pocketbase/pb_migrations/1693006389_updated_municipalities.js
  ui/pocketbase/pkg/.DS_Store
Labels: ui, size/L

#25 Remove darkmode
  ui/frontend/tailwind.config.cjs
Labels: size/XS

#26 11 UI login
  ui/frontend/src/routes/+layout.ts
  ui/frontend/src/routes/+page.svelte
  ui/frontend/src/routes/app/+page.svelte
  ui/frontend/src/routes/fake/+page.svelte
  ui/frontend/src/routes/login/+page.svelte
  ui/frontend/static/favicon.ico
  ui/frontend/static/favicon.png
  ui/frontend/static/images/360-logo.png
  ui/frontend/static/images/360-noscope.png
Labels: ui, size/L

#27 Some fixes
  ui/frontend/src/app.html
  ui/frontend/src/routes/login/+page.svelte
  ui/frontend/tailwind.config.cjs
Labels: ui, size/S

#28 feat: improve infra
  infra/.gitkeep
  infra/fluxcd/eck-stack.yaml
  infra/fluxcd/elasticsearch.yaml
  infra/fluxcd/ingress-es.yaml
  infra/fluxcd/ingress-kibana.yaml
  infra/fluxcd/kustomization.yaml
Labels: size/L

#29 feat: improve infra
  infra/fluxcd/eck-exporter.yaml
  infra/fluxcd/kustomization.yaml
Labels: size/M

#30 First Crawlers and crawler initial setup
  crawler/.env.example
  crawler/.gitignore
  crawler/EnergieverbrauchProPerson.py
  crawler/README.md
  crawler/lib/shared.py
  crawler/requirements.txt
Labels: size/L, crawler

#31 fix: helmreleases
  infra/fluxcd/eck-exporter.yaml
  infra/fluxcd/eck-stack.yaml
Labels: size/S

#32 fix: eck-stack
  infra/fluxcd/eck-stack.yaml
  infra/fluxcd/ingress-es.yaml
  infra/fluxcd/ingress-kibana.yaml
Labels: size/S

#34 fix misnaming of pvusage dictionary label
  crawler/EnergieverbrauchProPerson.py
Labels: size/XS

#37 17 uisub gemeindesurvey toggle
  ui/frontend/package-lock.json
  ui/frontend/package.json
  ui/frontend/src/hooks.client.ts
  ui/frontend/src/lib/components/base/ShowSurveyToggle.svelte
  ui/frontend/src/lib/stores/toggle.ts
  ui/frontend/src/routes/+layout.svelte
  ui/frontend/src/routes/app/+layout.svelte
  ui/frontend/src/routes/app/profile/+page.svelte
  ui/frontend/src/routes/login/+page.svelte
Labels: ui, size/XL

#38 feat(crawler): add municipality data
  crawler/mapping/convert.py
  crawler/mapping/data.html
  crawler/mapping/data.json
Labels: size/XXL

#41 Analyze phipu
  .gitignore
  .pre-commit-config.yaml
  analyze/pom.xml
  analyze/src/main/java/io/natron/noscope360/analyze/AnalyzeApplication.java
  analyze/src/main/java/io/natron/noscope360/analyze/config/SecurityConfig.java
  analyze/src/main/java/io/natron/noscope360/analyze/config/UserRole.java
  analyze/src/main/java/io/natron/noscope360/analyze/controller/ScaleController.java
  analyze/src/main/java/io/natron/noscope360/analyze/controller/SurveyController.java
  analyze/src/main/java/io/natron/noscope360/analyze/exception/GlobalControllerExceptionHandler.java
  analyze/src/main/java/io/natron/noscope360/analyze/model/Scale.java
  analyze/src/main/java/io/natron/noscope360/analyze/model/entity/IndicatorData.java
  analyze/src/main/java/io/natron/noscope360/analyze/model/entity/SurveyData.java
  analyze/src/main/java/io/natron/noscope360/analyze/model/enums/Dimension.java
  analyze/src/main/java/io/natron/noscope360/analyze/model/enums/Theme.java
  analyze/src/main/java/io/natron/noscope360/analyze/model/indicator/EnvironmentEnergyConsumptionIndicator.java
  analyze/src/main/java/io/natron/noscope360/analyze/model/indicator/EnvironmentEnergyQualityIndicator.java
  analyze/src/main/java/io/natron/noscope360/analyze/model/indicator/Indicator.java
  analyze/src/main/java/io/natron/noscope360/analyze/repository/IndicatorRepository.java
  analyze/src/main/java/io/natron/noscope360/analyze/repository/SurveyRepository.java
  analyze/src/main/java/io/natron/noscope360/analyze/service/ScaleService.java
  analyze/src/main/java/io/natron/noscope360/analyze/service/SurveyService.java
  analyze/src/main/java/io/natron/noscope360/analyze/service/UserService.java
  analyze/src/main/resources/application.properties
  analyze/src/main/resources/application.yml
Labels: size/XL

#42 feat: add mock stats
  ui/frontend/src/lib/components/base/ShowSurveyToggle.svelte
  ui/frontend/src/lib/components/data/InDecrease.svelte
  ui/frontend/src/lib/components/data/Stats.svelte
  ui/frontend/src/routes/app/+layout.svelte
  ui/frontend/src/routes/app/+page.svelte
Labels: ui, mocking

#45 Sg crawler
  crawler/README.md
  crawler/data/economy/.gitkeep
  crawler/data/environment/.gitkeep
  crawler/data/environment/energy/.gitkeep
  crawler/data/environment/energy/EnergieverbrauchProPerson.py
  crawler/data/social/.gitkeep
Labels: size/S

#47 fix: Datastructure labels
  crawler/README.md
  crawler/data/environment/energy/EnergieverbrauchProPerson.py
Labels: size/XS

#46 feat: dockerize analyzer, update ci
  .github/.DS_Store
  .github/workflows/docker-release.yml
  .github/workflows/ui-docker-release.yml
  .gitignore
  .pre-commit-config.yaml
  analyze/.gitkeep
  analyze/Dockerfile
  analyze/src/test/java/io/natron/noscope360/analyze/AnalyzeApplicationTests.java
  crawler/.env.example
  crawler/.gitkeep
  crawler/arcgis/config.py
  crawler/arcgis/models.py
  crawler/arcgis/service.py
  crawler/data/environment/energy/EnergieverbrauchProPerson.py
  crawler/lib/shared.py
  crawler/mapping/convert.py
  crawler/mapping/data.html
  crawler/mapping/data.json
  crawler/requirements.txt
  docker-compose.yaml
  infra/fluxcd/eck-exporter.yaml
  infra/fluxcd/eck-stack.yaml
  infra/fluxcd/ingress-es.yaml
  infra/fluxcd/ingress-kibana.yaml
  infra/fluxcd/ns.yaml
  ui/frontend/src/lib/pocketbase/generated-types.ts
  ui/pocketbase/pb_migrations/1671926343_updated_hooks.js
Labels: size/L

#51 feat: add deployments
  docker-compose.yaml
  infra/fluxcd/.sops.yaml
  infra/fluxcd/analyzer/configmap.yaml
  infra/fluxcd/analyzer/deployment.yaml
  infra/fluxcd/analyzer/kustomization.yaml
  infra/fluxcd/analyzer/secret.yaml
  infra/fluxcd/eck-stack/eck-exporter.yaml
  infra/fluxcd/eck-stack/eck-stack.yaml
  infra/fluxcd/eck-stack/ingress-es.yaml
  infra/fluxcd/eck-stack/ingress-kibana.yaml
  infra/fluxcd/eck-stack/kustomization.yaml
  infra/fluxcd/frontend/deployment.yaml
  infra/fluxcd/frontend/ingress.yaml
  infra/fluxcd/frontend/kustomization.yaml
  infra/fluxcd/kustomization.yaml
  ui/docker-compose.yaml
Labels: size/L

#52 chore: update secrets
  infra/fluxcd/analyzer/deployment.yaml
  infra/fluxcd/analyzer/kustomization.yaml
  infra/fluxcd/analyzer/sa.yaml
  infra/fluxcd/analyzer/secret.yaml
  infra/fluxcd/frontend/kustomization.yaml
  infra/fluxcd/frontend/sa.yaml
  infra/fluxcd/frontend/statefulset.yaml
Labels: size/M

#55 docs: add some initial docs
  README.md
  assets/360-noscope.png
  docs/.gitkeep
  docs/architecutre.md
  docs/getting-started.md
  docs/requirements.md
  ui/.DS_Store
  ui/pocketbase/.DS_Store
  ui/pocketbase/pkg/.DS_Store
Labels: size/L

#57 chore: reorg crawler
  crawler/data/environment/.gitkeep
  crawler/data/environment/energy/.gitkeep
  crawler/data/environment/energy/EnergieverbrauchProPerson.py
  crawler/mapping/1_create_indecies.py
  crawler/mapping/2_import_static_data.py
  crawler/mapping/dimensions.json
  crawler/mapping/themes.json
Labels: size/L

#60 feat: Municipality shapes upload
  crawler/.gitignore
  crawler/data/environment/biodiversity/protectedAreas/ProNatura.py
  crawler/data/geometry/GemeindeShapes.py
  crawler/data/geometry/upload.py
  crawler/requirements.txt
Labels: size/L

#61 19 uisub list
  ui/frontend/src/lib/components/base/ShowSurveyToggle.svelte
  ui/frontend/src/lib/components/data/Municipalities/MunicipalitiesFilter.svelte
  ui/frontend/src/lib/components/data/Municipalities/MunicipalitiesList.svelte
  ui/frontend/src/lib/components/data/Municipalities/MunicipalitiesListItem.svelte
  ui/frontend/src/lib/components/data/OneLineDiagram.svelte
  ui/frontend/src/lib/components/data/RatingLabel.svelte
  ui/frontend/src/lib/components/data/Stats.svelte
  ui/frontend/src/lib/mock/analyze-data.ts
  ui/frontend/src/lib/types/analyze-data.ts
  ui/frontend/src/routes/+layout.ts
  ui/frontend/src/routes/app/+layout.svelte
  ui/frontend/src/routes/app/+page.svelte
  ui/frontend/src/routes/app/profile/+page.svelte
  ui/frontend/src/routes/survey/[id]/+page.svelte
  ui/frontend/static/images/360-noscope-white.png
Labels: ui, size/XXL

#68 docs: add some docs
  README.md
  analyze/.dockerignore
  analyze/README.md
  crawler/README.md
  docker-compose.yaml
  docs/README.md
  docs/architecture.md
  docs/getting-started.md
  docs/requirements.md
  docs/submissions/BernHackt_ Jury Template Documentation.docx
  docs/submissions/BernHackt_ Jury Template Documentation.pdf
  infra/fluxcd/README.md
  infra/fluxcd/eck-stack/eck-exporter.yaml
  survey/.gitkeep
  ui/README.md
Labels: size/L

#71 docs: add architecture docs
  README.md
  docs/architecture.md
  docs/assets/architecture.png
  docs/assets/componentDiagram.drawio
  docs/assets/componentDiagram.jpg
Labels: size/L

#72 docs: fix image link
  docs/architecture.md
Labels: size/XS

#73 Analyze phipu
  analyze/src/main/java/io/natron/noscope360/analyze/controller/MunicipalityController.java
  analyze/src/main/java/io/natron/noscope360/analyze/controller/ScaleController.java
  analyze/src/main/java/io/natron/noscope360/analyze/controller/SurveyController.java
  analyze/src/main/java/io/natron/noscope360/analyze/model/Scale.java
  analyze/src/main/java/io/natron/noscope360/analyze/model/dto/AnswersDto.java
  analyze/src/main/java/io/natron/noscope360/analyze/model/dto/DimensionDto.java
  analyze/src/main/java/io/natron/noscope360/analyze/model/dto/IndicatorDto.java
  analyze/src/main/java/io/natron/noscope360/analyze/model/dto/MunicipalityDto.java
  analyze/src/main/java/io/natron/noscope360/analyze/model/dto/MunicipalityOverviewDto.java
  analyze/src/main/java/io/natron/noscope360/analyze/model/dto/MunicipalityStatsDto.java
  analyze/src/main/java/io/natron/noscope360/analyze/model/dto/QuestionDto.java
  analyze/src/main/java/io/natron/noscope360/analyze/model/dto/SurveyAnswersDto.java
  analyze/src/main/java/io/natron/noscope360/analyze/model/dto/SurveyDto.java
  analyze/src/main/java/io/natron/noscope360/analyze/model/dto/SurveyOverviewDto.java
  analyze/src/main/java/io/natron/noscope360/analyze/model/dto/SurveyStatsDto.java
  analyze/src/main/java/io/natron/noscope360/analyze/model/dto/ThemeDto.java
  analyze/src/main/java/io/natron/noscope360/analyze/model/entity/Dimension.java
  analyze/src/main/java/io/natron/noscope360/analyze/model/entity/IdentifiableValue.java
  analyze/src/main/java/io/natron/noscope360/analyze/model/entity/Indicator.java
  analyze/src/main/java/io/natron/noscope360/analyze/model/entity/Municipality.java
  analyze/src/main/java/io/natron/noscope360/analyze/model/entity/QualitativeData.java
  analyze/src/main/java/io/natron/noscope360/analyze/model/entity/QuantitativeData.java
  analyze/src/main/java/io/natron/noscope360/analyze/model/entity/SurveyData.java
  analyze/src/main/java/io/natron/noscope360/analyze/model/entity/Theme.java
  analyze/src/main/java/io/natron/noscope360/analyze/model/enums/Dimension.java
  analyze/src/main/java/io/natron/noscope360/analyze/model/enums/Theme.java
  analyze/src/main/java/io/natron/noscope360/analyze/model/indicator/EnvironmentEnergyConsumptionScaleMapping.java
  analyze/src/main/java/io/natron/noscope360/analyze/model/indicator/EnvironmentEnergyQualityIndicator.java
  analyze/src/main/java/io/natron/noscope360/analyze/model/indicator/EnvironmentEnergyQualityScaleMapping.java
  analyze/src/main/java/io/natron/noscope360/analyze/model/indicator/Indicator.java
  analyze/src/main/java/io/natron/noscope360/analyze/model/indicator/IndicatorScaleMapping.java
  analyze/src/main/java/io/natron/noscope360/analyze/model/indicator/ScaleConvertable.java
  analyze/src/main/java/io/natron/noscope360/analyze/model/indicator/ScaleMappingDelegator.java
  analyze/src/main/java/io/natron/noscope360/analyze/repository/DimensionRepository.java
  analyze/src/main/java/io/natron/noscope360/analyze/repository/IndicatorRepository.java
  analyze/src/main/java/io/natron/noscope360/analyze/repository/MunicipalityRepository.java
  analyze/src/main/java/io/natron/noscope360/analyze/repository/QualitativeDataRepository.java
  analyze/src/main/java/io/natron/noscope360/analyze/repository/QuantitativeDataRepository.java
  analyze/src/main/java/io/natron/noscope360/analyze/repository/SurveyRepository.java
  analyze/src/main/java/io/natron/noscope360/analyze/repository/ThemeRepository.java
  analyze/src/main/java/io/natron/noscope360/analyze/service/IndicatorNameExtractor.java
  analyze/src/main/java/io/natron/noscope360/analyze/service/MunicipalityService.java
  analyze/src/main/java/io/natron/noscope360/analyze/service/ScaleService.java
  analyze/src/main/java/io/natron/noscope360/analyze/service/SurveyService.java
  crawler/data/environment/.gitkeep
  crawler/data/environment/energy/.gitkeep
  ui/.DS_Store
  ui/pocketbase/.DS_Store
  ui/pocketbase/pkg/.DS_Store
Labels: size/XXL

#69 22 uisub analyze + animation
  .github/workflows/ci.yml
  ui/frontend/package-lock.json
  ui/frontend/package.json
  ui/frontend/src/lib/components/base/GlowingButton.svelte
  ui/frontend/src/lib/components/base/ToggleConfetti.svelte
  ui/frontend/src/lib/components/data/Diagrams/BarChart.svelte
  ui/frontend/src/lib/components/data/Diagrams/RadarChart.svelte
  ui/frontend/src/lib/components/data/Diagrams/bar-data.ts
  ui/frontend/src/lib/components/data/Diagrams/data.ts
  ui/frontend/src/lib/components/data/Diagrams/radar-data.ts
  ui/frontend/src/lib/components/data/Municipalities/MunicipalitiesFilter.svelte
  ui/frontend/src/lib/components/data/Municipalities/MunicipalitiesListItem.svelte
  ui/frontend/src/lib/components/data/OneLineDiagram.svelte
  ui/frontend/src/lib/components/data/Stats.svelte
  ui/frontend/src/lib/components/data/Surveys/SurveysFilter.svelte
  ui/frontend/src/routes/app/+layout.svelte
  ui/frontend/src/routes/app/+page.svelte
  ui/frontend/src/routes/app/analyze/+page.svelte
  ui/frontend/src/routes/test/+page.svelte
Labels: ui, size/XL

#76 fix(docs): Set correct license
  README.md
Labels: size/XS

#79 feat: add rec
  ui/Dockerfile
  ui/frontend/src/lib/components/base/Recommendations.svelte
  ui/frontend/src/lib/components/base/ShowSurveyToggle.svelte
  ui/frontend/src/lib/components/data/Diagrams/BarChart.svelte
  ui/frontend/src/lib/components/data/Diagrams/RadarChart.svelte
  ui/frontend/src/lib/components/data/Diagrams/bar-data.ts
  ui/frontend/src/lib/components/data/Municipalities/MunicipalitiesFilter.svelte
  ui/frontend/src/lib/components/data/Municipalities/MunicipalitiesListItem.svelte
  ui/frontend/src/lib/components/data/Stats.svelte
  ui/frontend/src/lib/components/data/Surveys/SurveysFilter.svelte
  ui/frontend/src/routes/app/+layout.svelte
  ui/frontend/src/routes/app/+page.svelte
  ui/frontend/src/routes/app/analyze/+page.svelte
  ui/frontend/src/routes/app/profile/+page.svelte
  ui/frontend/tailwind.config.cjs
Labels: ui, size/L
